export const MY_FAKE_CONTRACTS = [
  {
    title: "Office Lease Agreement",
    startDateString: "Jan 1 2024",
    endDateString: "Dec 31 2024",
    holderName: "Alice Johnson",
    imageUrl: "https://placehold.co/141x200.png",
  },
  {
    title: "Service Agreement",
    startDateString: "Mar 15 2024",
    endDateString: "Sep 15 2024",
    holderName: "Bob Smith",
    imageUrl: "https://placehold.co/141x200.png",
  },
  {
    title: "Maintenance Contract",
    startDateString: "Jun 1 2024",
    endDateString: "Jun 1 2025",
    holderName: "Carol Davis",
    imageUrl: "https://placehold.co/141x200.png",
  },
  {
    title: "Consulting Agreement",
    startDateString: "Feb 1 2024",
    endDateString: "Feb 1 2025",
    holderName: "David Brown",
    imageUrl: "https://placehold.co/141x200.png",
  },
  {
    title: "Supply Contract",
    startDateString: "May 1 2024",
    endDateString: "Nov 1 2024",
    holderName: "Emma Wilson",
    imageUrl: "https://placehold.co/141x200.png",
  },
  {
    title: "Rental Agreement",
    startDateString: "Jul 1 2024",
    endDateString: "Jul 1 2025",
    holderName: "Frank Miller",
    imageUrl: "https://placehold.co/141x200.png",
  },
  {
    title: "Consultancy Contract",
    startDateString: "Apr 20 2024",
    endDateString: "Oct 20 2024",
    holderName: "Grace White",
    imageUrl: "https://placehold.co/141x200.png",
  },
  {
    title: "IT Services Agreement",
    startDateString: "Sep 1 2024",
    endDateString: "Mar 1 2025",
    holderName: "Henry Green",
    imageUrl: "https://placehold.co/141x200.png",
  },
  {
    title: "Construction Contract",
    startDateString: "Aug 10 2024",
    endDateString: "Feb 10 2025",
    holderName: "Ivy Brown",
    imageUrl: "https://placehold.co/141x200.png",
  },
  {
    title: "Delivery Service Agreement",
    startDateString: "Nov 15 2024",
    endDateString: "May 15 2025",
    holderName: "Jack Blue",
    imageUrl: "https://placehold.co/141x200.png",
  },
];
