import { BillDto } from "@/lib/dtos";
import { BillStatus } from "@/shared/constants";

export const FAKE_BILL_DATA: BillDto[] = [
  {
    title: "Electricity Bill",
    description: "Monthly electricity bill for the residence.",
    amount: 120.75,
    recipientName: "Energy Supplier Inc.",
    recipientAddress: "123 Power Lane, Energy City, Country",
    billType: "Utility",
    status: BillStatus.DUE,
    dueDateString: "Oct 15, 2024",
    createdDateString: "Sep 1, 2024",
  },
  {
    title: "Internet Service",
    description: "Monthly charge for internet service.",
    amount: 65.0,
    recipientName: "Internet Provider Ltd.",
    recipientAddress: "456 Data Drive, NetTown, Country",
    billType: "Subscription",
    status: BillStatus.SETTLED,
    dueDateString: "Oct 5, 2024",
    createdDateString: "Sep 1, 2024",
  },
  {
    title: "Water Bill",
    description: "Quarterly water usage charge.",
    amount: 45.3,
    recipientName: "Water Services Corp.",
    recipientAddress: "789 Aqua Avenue, Waterville, Country",
    billType: "Utility",
    status: BillStatus.OVERDUE,
    dueDateString: "Sep 30, 2024",
    createdDateString: "Jul 1, 2024",
  },
  {
    title: "Rent",
    description: "Monthly rent for the apartment.",
    amount: 1500.0,
    recipientName: "Landlord Name",
    recipientAddress: "101 Rental Road, Rentville, Country",
    billType: "Rent",
    status: BillStatus.DUE,
    dueDateString: "Oct 1, 2024",
    createdDateString: "Sep 1, 2024",
  },
  {
    title: "Gym Membership",
    description: "Monthly membership fee for the local gym.",
    amount: 40.0,
    recipientName: "Local Gym Center",
    recipientAddress: "202 Fitness St., Workout City, Country",
    billType: "Subscription",
    status: BillStatus.SETTLED,
    dueDateString: "Oct 20, 2024",
    createdDateString: "Sep 1, 2024",
  },
];
